server:
  port: 8090

spring:
  application:
    name: API_GATEWAY
  cloud:
    gateway:
      routes:
      - id: HOTEL-CUSTOMER-SERVICE
        uri: 
            lb://HOTEL-CUSTOMER-SERVICE
        predicates:
        - Path=/hotel/customer/** 
      - id: HOTEL-EMPLOYEE-SERVICE
        uri: 
            lb://HOTEL-EMPLOYEE-SERVICE
        predicates:
        - Path=/hotel/employee/** 
      - id: HOTEL-ROOM-SERVICE
        uri: 
            lb://HOTEL-ROOM-SERVICE
        predicates:
        - Path=/hotel/room/**
      - id: HOTEL-LOGIN-SERVICE
        uri: 
            lb://HOTEL-LOGIN-SERVICE
        predicates:
        - Path=/hotel/login/**
     
        
      
        



